version: '3'

services:
  bitbucket:
    image: atlassian/bitbucket-server
    volumes:
      - bitbucketdata:/var/atlassian/application-data/bitbucket
    ports:
      - '7990:7990'
      - '7999:7999'
    environment:
      - 'BITBUCKET_PROXY_NAME='


volumes:
  bitbucketdata: