FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/jenkins-nginx.conf /etc/nginx/conf.d/test-jenkins-nginx.conf
SHELL ["/bin/bash", "-c"]
RUN openssl req -x509 -nodes -days 365 \ 
    -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt -config <(echo "CN\n:")


