version: '3.8'
services:

  db_host:
    # container_name: db        // not supported by 'docker stack deploy'
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-8:/var/lib/mysql
    networks:
      - jenkins-nginx-network
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == raflman-pc ]



volumes:
  mysql-data-8:

networks:
  jenkins-nginx-network:

