version: '3.7'
services:

        gitlab_server:
                image: raflman/gitlab-test:latest
                restart: on-failure
                hostname: "jenkins.local"
                environment:
                  GITLAB_OMNIBUS_CONFIG: |
                          external_url "https://jenkins.local:8090"
                          gitlab_rails['gitlab_shell_ssh_port'] = 2222
                          gitlab_rails['packages_enabled'] = true

                          nginx['ssl_certificate'] = "/etc/ssl/certs/localhost.crt"
                          nginx['ssl_certificate_key'] = "/etc/ssl/private/localhost.key"
                          nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"
                          nginx['custom_gitlab_server_config'] = "error_page 497 https://$$host:$$server_port$$request_uri;"

                          registry_external_url "https://jenkins.local:8091"
                          registry_nginx['ssl_certificate'] = "/etc/ssl/certs/docker-registry.crt"
                          registry_nginx['ssl_certificate_key'] = "/etc/ssl/private/docker-registry.key"
                          registry_nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"

                          letsencrypt['enable'] = false


                ports:
                  - '8090:8090'
                  - '8091:8091'
                  - '2222:22'
                volumes:
                  - gitlab-etc:/etc/gitlab
                  - gitlab-logs:/var/log/gitlab
                  - gitlab-data:/var/opt/gitlab
                networks:
                  - jenkins-nginx-network

volumes:
  gitlab-etc:
  gitlab-logs:
  gitlab-data:

networks:
  jenkins-nginx-network:

