version: '3.7'
services:

        gitlab_server:
                image: raflman/gitlab-ce:multiple-host
                restart: on-failure
                environment:
                  GITLAB_OMNIBUS_CONFIG: |
                          external_url "http://gitlab"
                          gitlab_rails['gitlab_shell_ssh_port'] = 2222
                          gitlab_rails['packages_enabled'] = true
                          grafana['disable_login_form'] = false
                          grafana['admin_password'] = 'admin'
                          registry_external_url "http://gitlab:5050"

#                          external_url "https://localhost:8090"
#                          gitlab_rails['gitlab_shell_ssh_port'] = 2222
#                          gitlab_rails['packages_enabled'] = true
#                          grafana['disable_login_form'] = false
#                          grafana['admin_password'] = 'admin'
#
#
#                          nginx['ssl_certificate'] = "/etc/ssl/certs/localhost.crt"
#                          nginx['ssl_certificate_key'] = "/etc/ssl/private/localhost.key"
#                          nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"
#                          nginx['custom_gitlab_server_config'] = "error_page 497 https://$$host:$$server_port$$request_uri;"
#
#                          registry_external_url "https://jenkins.local:8091"
#                          registry_nginx['ssl_certificate'] = "/etc/ssl/certs/docker-registry.crt"
#                          registry_nginx['ssl_certificate_key'] = "/etc/ssl/private/docker-registry.key"
#                          registry_nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"
#
#                          letsencrypt['enable'] = false

          #                         This is disabled by default in gitlab docker image.
          #                         node_exporter['enable'] = true

                ports:
                  - '8090:8090'
                  - '9090:9090'
                  - '8091:8091'
                  - '2222:22'
                volumes:
                  - gitlab-etc:/etc/gitlab
                  - gitlab-logs:/var/log/gitlab
                  - gitlab-data:/var/opt/gitlab
                networks:
                  - jenkins-nginx-network

volumes:
  gitlab-etc:
  gitlab-logs:
  gitlab-data:

networks:
  jenkins-nginx-network:

