version: '3.7'
services:

<<<<<<< HEAD
  gitlab_server:
    image: 'jenkins-gitlab'
    build:
      context: .
    restart: 'no'
    hostname: "jenkins.local"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://jenkins.local"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        nginx['ssl_certificate'] = "/etc/ssl/certs/localhost-self-signed.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/localhost-self-signed.key"
        nginx['custom_gitlab_server_config'] = "error_page 497 https://$$host:$$server_port$$request_uri;"

        registry_external_url "https://jenkins.local:8091"
        registry_nginx['ssl_certificate'] = "/etc/ssl/certs/localhost-self-signed.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/ssl/certs/localhost-self-signed.key"

        # Uncomment this if you want to install your certicate
        # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
        letsencrypt['enable'] = false

    ports:
      - '8080:8080'
      - '443:443'
      - '8091:8091'
      - '2222:22'
    volumes:
      - gitlab-etc:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - jenkins-nginx-network


volumes:
  gitlab-etc:
  gitlab-logs:
  gitlab-data:
=======
        gitlab_server:
#                image: raflman/gitlab-ce:multiple-host
                image: gitlab-test:21KAS
                restart: on-failure
                environment:
                  GITLAB_OMNIBUS_CONFIG: |
                          letsencrypt['enable'] = false
                          external_url "https://gitlab:8090"
                          gitlab_rails['gitlab_shell_ssh_port'] = 2222
                          nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
                          nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"

                ports:
                  - '8090:8090'
                  - '9090:9090'
                  - '8091:8091'
                  - '2222:22'
                  - '5050:5050'
                volumes:
                  - /home/izzetcan/Documents/gitlab-data/etc:/etc/gitlab
                  - /home/izzetcan/Documents/gitlab-data/logs:/var/log/gitlab
                  - /home/izzetcan/Documents/gitlab-data/data:/var/opt/gitlab
                networks:
                  - jenkins-nginx-network

# volumes:
#   gitlab-etc:
#   gitlab-logs:
#   gitlab-data:
>>>>>>> multiple-host

networks:
  jenkins-nginx-network:

<<<<<<< HEAD
=======
d
>>>>>>> multiple-host
