version: '3.7'
services:

  gitlab_server_test:
    image: 'gitlab/gitlab-ce:13.4.1-ce.0'
    restart: always
    hostname: "jenkins.local"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://jenkins.local:12345"
        gitlab_rails['gitlab_shell_ssh_port'] = 330

        # Uncomment this if you want to install your certicate
        # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
        # letsencrypt['enable'] = false

    ports:
      - '12345:12345'
      - '330:22'
    volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - jenkins-nginx-network

volumes:
  gitlab-conf:
  gitlab-log:
  gitlab-data:

networks:
  jenkins-nginx-network:

