version: '3.7'
services:

  gitlab_server_test:
    image: 'gitlab/gitlab-ce:13.4.1-ce.0'
    restart: always
    hostname: "jenkins.local"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://jenkins.local:8090"
        gitlab_rails['gitlab_shell_ssh_port'] = 24

        # Uncomment this if you want to install your certicate
        # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
        #letsencrypt['enable'] = false

    ports:
      - '8090:8090'
      - '24:22'
    volumes:
      - 82e8ce737c67942f4c1f4c32ab4650cc62ecba8c358c99aa4c07574e60075254:/etc/gitlab
      - 545621b3a2da0992bccceb54c453918976f904766735d65a9929b5ed47da2976:/var/log/gitlab
      - 839cbf96e2205728ac0fe5b79bddfc7945da8f9b7165f10190d0952240636066:/var/opt/gitlab
      # networks:
      # - jenkins-nginx-network

volumes:
  82e8ce737c67942f4c1f4c32ab4650cc62ecba8c358c99aa4c07574e60075254:
    external: true

  545621b3a2da0992bccceb54c453918976f904766735d65a9929b5ed47da2976:
    external: true

  839cbf96e2205728ac0fe5b79bddfc7945da8f9b7165f10190d0952240636066:
    external: true

  #networks:
  #jenkins-nginx-network:

