version: '3.8'
services:

        remote_host:
                image: raflman/jenkins-centos8:multiple-host
                networks:
                       - jenkins-nginx-network
                deploy:
                        replicas: 1
                        placement:
                                constraints: [ node.hostname == izzetcan-pc ]

                        resources:
                                limits:
                                        memory: 1024M
                                        cpus: '0.5'
                                reservations:
                                        memory: 128M
                                        cpus: '0.20'

        gitlab_server:
                image: raflman/gitlab-ce-subgit:13.10.4
                environment:
                        GITLAB_OMNIBUS_CONFIG: |
                                external_url "http://gitlab"
                                gitlab_rails['gitlab_shell_ssh_port'] = 2222
                                gitlab_rails['packages_enabled'] = true
                                grafana['disable_login_form'] = false
                                grafana['admin_password'] = 'admin'
                                registry_external_url "http://gitlab:5050"

                ports:
                        - '2222:22'
                volumes:
                        - gitlab-etc:/etc/gitlab
                        - gitlab-logs:/var/log/gitlab
                        - gitlab-data:/var/opt/gitlab
                networks:
                        - jenkins-nginx-network
                deploy:
                        mode: global
                        placement:
                                constraints: [ node.hostname == izzetcan-pc ]
                        restart_policy:
                                condition: any
                                delay: 10s
                                window: 300s

                        resources:
                                limits:
                                        memory: 4096M
                                        cpus: '2'
                                reservations:
                                        memory: 2048M
                                        cpus: '1'

        nginx:
                image: raflman/nginx:gitlab
                ports:
                        - "443:443"
                        - "80:80"
                networks:
                        - jenkins-nginx-network
                depends_on:
                        - gitlab_server
                deploy:
                        replicas: 1
                        placement:
                                constraints: [ node.hostname == izzetcan-pc ]
                        restart_policy:
                                condition: any
                                delay: 20s
                        resources:
                                limits:
                                        memory: 1024M
                                        cpus: '0.5'
                                reservations:
                                        memory: 512M
                                        cpus: '0.20'


volumes:
        gitlab-etc:
        gitlab-logs:
        gitlab-data:

networks:
        jenkins-nginx-network:

