version: '3.7'
services:

        gitlab_server:
                image: 'gitlab/gitlab-ce:13.4.1-ce.0'
                restart: always
                hostname: "localhost"
                environment:
                  GITLAB_OMNIBUS_CONFIG: |
                    external_url "https://localhost:8090"
                    gitlab_rails['gitlab_shell_ssh_port'] = 23

                    # Uncomment this if you want to install your certicate
                    # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work                    
                    #letsencrypt['enable'] = false

                ports: 
                        - '8090:8090'
                        - '23:22'
                          #volumes:
                          # - 1fa5493f64ad615ca99e6f177343cf19bc5fd2349d63974b5f011ff9cf7ddd0f:/etc/gitlab
                          # - 077dd035a1f373accb323ad5dc3bdea555e1d7edcc87f7f2ff341dd9ecbdd955:/var/log/gitlab
                          # - 2e0ae3cd01ae2b223111e4f2af76ae85bf115726630e741a8207dfa9e9e75e55:/var/opt/gitlab
                          # networks:
                          # - jenkins-nginx-network

                          #volumes:
                          #  1fa5493f64ad615ca99e6f177343cf19bc5fd2349d63974b5f011ff9cf7ddd0f:
                          # 077dd035a1f373accb323ad5dc3bdea555e1d7edcc87f7f2ff341dd9ecbdd955:
                          # 2e0ae3cd01ae2b223111e4f2af76ae85bf115726630e741a8207dfa9e9e75e55:

                          #networks:
                          #jenkins-nginx-network:

