version: '3.7'
services:

        
        db_host:
                container_name: db
                image: mysql:8
                environment:
                       - "MYSQL_ROOT_PASSWORD=1234"
                volumes:
                       - mysql-data-8:/var/lib/mysql
                networks:
                       - jenkins-nginx-network

        remote_host:
                image: jenkins-centos8
                build:
                       context: centos8
                networks:
                       - jenkins-nginx-network
                  
        jenkins:
                image: jenkins/jenkins:2.249.1-lts-centos
                privileged: true
                user: root
                #environment:
                       #- "JAVA_OPTS=-Xmx256m"
                ports:
                        - "50000:50000"
                          #container_name: jenkins-container
                volumes:
                        - jenkins-log:/var/log/jenkins
                        - jenkins-data:/var/jenkins_home
                        - jenkins-java-ext-dirs:/usr/java/packages/lib/ext
                          #- certbot-conf:/etc/letsencrypt
                          #- certbot-www:/var/www/certbot
                          #- /var/run/docker.sock:/var/run/docker.sock
                          #- /usr/local/bin/docker:/usr/local/bin/docker
                networks:
                        - jenkins-nginx-network

                depends_on:
                        - db_host
                        - gitlab_server
                        - remote_host

        nginx:
                image:  jenkins-nginx
                build:
                        context: nginx
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - jenkins-nginx-network

                depends_on:
                        - jenkins
                        - db_host
                        - gitlab_server
                        - remote_host
        
                          # certbot:
                          # image: certbot/certbot
                          # restart: unless-stopped
                          # volumes:
                          # - certbot-conf:/etc/letsencrypt
                          # - certbot-www:/var/www/certbot
                          # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

        gitlab_server:
                image: jenkins-gitlab
                build:
                        context: gitlab
                restart: 'no'
                hostname: "jenkins.local"
                environment:
                        GITLAB_OMNIBUS_CONFIG: |
                                external_url "https://jenkins.local:8090"
                                gitlab_rails['gitlab_shell_ssh_port'] = 2222

                                nginx['ssl_certificate'] = "/etc/ssl/certs/localhost.crt"
                                nginx['ssl_certificate_key'] = "/etc/ssl/private/localhost.key"
                                nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"
                                nginx['custom_gitlab_server_config'] = "error_page 497 https://$$host:$$server_port$$request_uri;"

                                registry_external_url "https://jenkins.local:8091"
                                registry_nginx['ssl_certificate'] = "/etc/ssl/certs/docker-registry.crt"
                                registry_nginx['ssl_certificate_key'] = "/etc/ssl/private/docker-registry.key"
                                registry_nginx['ssl_dhparam'] = "/etc/ssl/certs/dhparam.pem"

                                # Uncomment this if you want to install your certicate
                                # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
                                letsencrypt['enable'] = false

                ports:
                        - '8090:8090'
                        - '8091:8091'
                        - '2222:22'
                volumes:
                        - gitlab-etc:/etc/gitlab
                        - gitlab-logs:/var/log/gitlab
                        - gitlab-data:/var/opt/gitlab
                networks:
                        - jenkins-nginx-network
volumes:
        jenkins-log:
        jenkins-data:
        jenkins-java-ext-dirs:
        mysql-data-8:
        gitlab-etc:
        gitlab-logs:
        gitlab-data:

networks:
        jenkins-nginx-network:

