version: '3.7'
services:

        
        db_host:
                container_name: db
                image: mysql:8
                environment:
                       - "MYSQL_ROOT_PASSWORD=1234"
                volumes:
                       - mysql-data-8:/var/lib/mysql
                networks:
                       - jenkins-nginx-network



        remote_host:
                container_name: remote-host
                image: remote-host
                build:
                       context: centos8
                networks:
                       - jenkins-nginx-network
                  
        jenkins:
                image: jenkins/jenkins:2.249.1-lts-centos
                privileged: true
                user: root
                #environment:
                       #- "JAVA_OPTS=-Xmx256m"
                ports:
                        - "50000:50000"
                          #container_name: jenkins-container
                volumes:
                        - jenkins-log:/var/log/jenkins
                        - jenkins-data:/var/jenkins_home

                          #- certbot-conf:/etc/letsencrypt
                          #- certbot-www:/var/www/certbot
                          #- /var/run/docker.sock:/var/run/docker.sock
                          #- /usr/local/bin/docker:/usr/local/bin/docker
                networks:
                        - jenkins-nginx-network
        nginx:
                build: ./nginx
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - jenkins-nginx-network
        
                          # certbot:
                          # image: certbot/certbot
                          # restart: unless-stopped
                          # volumes:
                          # - certbot-conf:/etc/letsencrypt
                          # - certbot-www:/var/www/certbot
                          # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

        gitlab_server:
                image: 'gitlab-ce:test'
                restart: 'no'
                hostname: "jenkins.local"
                environment:
                        GITLAB_OMNIBUS_CONFIG: |
                                external_url "https://jenkins.local:8090"
                                gitlab_rails['gitlab_shell_ssh_port'] = 2222

                                nginx['ssl_certificate'] = "/etc/ssl/certs/localhost-self-signed.crt"
                                nginx['ssl_certificate_key'] = "/etc/ssl/certs/localhost-self-signed.key"
                                nginx['custom_gitlab_server_config'] = "error_page 497 https://\$host:\$server_port\$request_uri;"

                                # Uncomment this if you want to install your certicate
                                # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
                                letsencrypt['enable'] = false

                ports:
                        - '8090:8090'
                        - '2222:22'
                volumes:
                        - gitlab-etc:/etc/gitlab
                        - gitlab-logs:/var/log/gitlab
                        - gitlab-data:/var/opt/gitlab
                networks:
                        - jenkins-nginx-network
volumes:
        jenkins-log:
        jenkins-data:
        mysql-data-8:
        gitlab-etc:
        gitlab-logs:
        gitlab-data:

networks:
        jenkins-nginx-network:

