version: '3.8'
services:

        gitlab_server:
                image: 'gitlab-ce:test'
                restart: 'no'
                hostname: "localhost"
                environment:
                        GITLAB_OMNIBUS_CONFIG: |
                                external_url "https://localhost:8090"
                                gitlab_rails['gitlab_shell_ssh_port'] = 23

                                nginx['ssl_certificate'] = "/etc/ssl/certs/localhost-self-signed.crt"
                                nginx['ssl_certificate_key'] = "/etc/ssl/certs/localhost-self-signed.key"

                                # Uncomment this if you want to install your certicate
                                # https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work
                                letsencrypt['enable'] = false

                ports:
                        - '8090:8090'
                        - '23:22'
                volumes:
                        - gitlab-etc:/etc/gitlab
                        - gitlab-logs:/var/log/gitlab
                        - gitlab-data:/var/opt/gitlab
                networks:
                        - jenkins-nginx-network

volumes:
        gitlab-etc:
        gitlab-logs:
        gitlab-data:

networks:
        jenkins-nginx-network:

